import SwiftUI

struct Favourites: Identifiable {
    let id = UUID()
    let title: String
    let cuisine: String
    let timeToMake: Int
    let ingredients: [String]
    let instructions: [String]
    let imageName: String
}

class Favourites_Model: ObservableObject {
    @Published var Favourites_data: [Favourites] = [
        Favourites(title: "Pizza Margherita", 
                   cuisine: "Italian", 
                   timeToMake: 60, 
                   ingredients: ["Pizza Crust", "Tomato Sauce", "Mozzarella Cheese", "Fresh Basil", "Olive Oil", "Salt"],
                   instructions: ["Preheat oven to 450 degrees F (230 degrees C).",
                                  "Make the pizza dough:",
                                  "a. In a large bowl, whisk together the flour, salt, and yeast.",
                                  "b. Add the warm water and olive oil, and stir until the dough comes together.",
                                  "c. Turn the dough out onto a lightly floured surface and knead for 5-10 minutes, or until smooth and elastic.",
                                  "d. Place the dough in a greased bowl, cover with plastic wrap, and let rise in a warm place for 30-45 minutes, or until doubled in size.",
                                  "Make the pizza sauce:",
                                  "a. In a medium saucepan, heat the olive oil over medium heat.",
                                  "b. Add the garlic and cook for 30 seconds, or until fragrant.",
                                  "c. Add the crushed tomatoes, oregano, basil, salt, and pepper.",
                                  "d. Bring to a simmer and cook for 15-20 minutes, or until the sauce has thickened.",
                                  "Assemble the pizza:",
                                  "a. Punch down the dough and divide it into two balls.",
                                  "b. On a lightly floured surface, roll out one ball of dough into a 12-inch circle.",
                                  "c. Place the dough circle on a lightly greased pizza pan or baking sheet.",
                                  "d. Spread the pizza sauce evenly over the dough.",
                                  "e. Sprinkle the mozzarella cheese evenly over the sauce.",
                                  "f. Add your desired toppings.",
                                  "Bake the pizza for 10-15 minutes, or until the crust is golden brown and the cheese is melted and bubbly.",
                                  "Let the pizza cool for a few minutes before slicing and serving."],
                   imageName: "pizza-margherita"),
        Favourites(title: "Pasta Carbonara", 
                   cuisine: "Italian", 
                   timeToMake: 30, 
                   ingredients: [
                    "Guanciale", "Eggs", "Pecorino Romano cheese", "Black pepper"],
                   instructions: ["Boil water in a large pot and add salt.",
                                  "Cook the pasta according to the package instructions until al dente.",
                                  "While the pasta is cooking, prepare the sauce:",
                                  "a. In a skillet, cook the guanciale until crispy. If unavailable, pancetta or bacon can be used as a substitute.",
                                  "b. In a bowl, whisk together eggs, Pecorino Romano cheese, and black pepper.",
                                  "c. Once the guanciale is cooked, remove it from the heat.",
                                  "d. When the pasta is ready, drain it and add it to the skillet with the guanciale. Toss to coat the pasta in the rendered fat.",
                                  "e. Remove the skillet from heat and quickly pour the egg and cheese mixture over the pasta, tossing continuously to create a creamy sauce.",
                                  "Serve immediately, garnished with additional Pecorino Romano cheese and black pepper."],
                   imageName: "pasta-carbonara"),
        Favourites(title: "Palak Paneer", 
                   cuisine: "Indian", 
                   timeToMake: 40, 
                   ingredients: ["Paneer", "Spinach", "Onions", "Ginger", "Garlic", "Turmeric powder", "Red chili powder", "Garam masala", "Salt"],
                   instructions: ["Rinse spinach thoroughly and blanch in boiling water for 2-3 minutes. Drain and transfer to a bowl of ice water to cool. Drain again and blend into a smooth puree.",
                                  "In a pan, heat oil or ghee over medium heat. Add cumin seeds and let them splutter.",
                                  "Add finely chopped onions and sauté until golden brown.",
                                  "Add ginger-garlic paste and sauté until the raw smell disappears.",
                                  "Add tomato puree and cook until the oil separates from the mixture.",
                                  "Add turmeric powder, red chili powder, and garam masala. Mix well and cook for a couple of minutes.",
                                  "Add the spinach puree and cook for 5-7 minutes, stirring occasionally.",
                                  "Add paneer cubes and cook for an additional 3-5 minutes.",
                                  "Add salt to taste and adjust the consistency with water if needed.",
                                  "Finish with a drizzle of cream (optional) and simmer for a few more minutes.",
                                  "Palak Paneer is ready to be served. Garnish with a dollop of butter or cream and serve with naan or rice."],
                   imageName: "palak-paneer"),
        Favourites(title: "Paneer Tikka", 
                   cuisine: "Indian", 
                   timeToMake: 45,
                   ingredients: ["Paneer", "Yogurt", "Ginger-garlic paste", "Garam masala", "Turmeric powder", "Red chili powder", "Salt", "Oil"],
                   instructions: ["Marinate the paneer:",
                                  "a. In a bowl, mix together paneer, yogurt, ginger-garlic paste, garam masala, turmeric powder, red chili powder, salt, and oil.",
                                  "b. Ensure the paneer pieces are well-coated with the marinade.",
                                  "c. Cover the bowl and let it marinate for at least 1-2 hours in the refrigerator.",
                                  "Preheat the oven to 200 degrees Celsius (392 degrees Fahrenheit).",
                                  "Thread the marinated paneer onto skewers, alternating with bell peppers and onions if desired.",
                                  "Place the skewers on a baking tray lined with parchment paper.",
                                  "Bake in the preheated oven for 15-20 minutes or until the paneer is cooked and has a golden-brown color.",
                                  "Garnish with lemon wedges and fresh coriander before serving."],
                   imageName: "paneer-tikka"),
        Favourites(title: "Sushi", 
                   cuisine: "Japanese", 
                   timeToMake: 60,         
                   ingredients: ["Vinegared rice", "Nori sheets", "Seafood (e.g., tuna, salmon, shrimp)", "Vegetables (e.g., cucumber, avocado, carrot)"],
                   instructions: ["Cook sushi rice according to package instructions.",
                                  "While the rice is cooking, prepare the sushi vinegar by mixing rice vinegar, sugar, and salt in a bowl. Heat the mixture slightly to dissolve the sugar and salt. Let it cool.",
                                  "Spread the cooked rice on a large plate or a sushi mat. Drizzle the sushi vinegar over the rice and gently fold it in, fanning the rice to cool it down.",
                                  "Place a sheet of nori (seaweed) on a bamboo sushi rolling mat. Wet your fingers to prevent sticking, and spread a thin, even layer of rice on the nori, leaving about an inch at the top.",
                                  "Add your desired ingredients along the bottom edge of the rice. This may include a strip of fish, avocado, cucumber, or other vegetables.",
                                  "Roll the sushi tightly from the bottom using the bamboo mat to shape it. Seal the edge with a little water to help it stick.",
                                  "Using a sharp knife, slice the rolled sushi into bite-sized pieces.",
                                  "Serve the sushi with soy sauce, pickled ginger, and wasabi.",
                                  "Enjoy your homemade sushi!"],
                   imageName: "sushi"),
        Favourites(title: "Pad Thai", 
                   cuisine: "Thai", 
                   timeToMake: 35, 
                   ingredients: ["Rice noodles", "Tamarin paste", "Fish sauce", "Palm sugar", "Dried shrimp", "Peanuts", "Bean sprouts", "Eggs", "Tofu (optional)", "Chicken (optional)", "Shrimp (optional)"],
                   instructions: ["Soak rice noodles in warm water for 30-45 minutes, or until softened. Drain and set aside.",
                                  "In a wok or large skillet, heat vegetable oil over medium-high heat.",
                                  "Add tofu, chicken, or shrimp and cook until browned and cooked through. Set aside.",
                                  "In the same wok, add more oil if needed. Add garlic and sauté for 30 seconds, or until fragrant.",
                                  "Add soaked and drained rice noodles to the wok. Stir-fry for 2-3 minutes, breaking up the noodles.",
                                  "Push the noodles to the side of the wok. Crack the eggs into the wok and scramble until just set.",
                                  "Add bean sprouts, green onions, and crushed peanuts. Stir to combine.",
                                  "Pour the Pad Thai sauce over the noodles and toss everything together.",
                                  "Add the cooked tofu, chicken, or shrimp back to the wok. Toss until everything is well-coated.",
                                  "Serve Pad Thai hot, garnished with additional peanuts, lime wedges, and cilantro.",],
                   imageName: "pad-thai"),
        Favourites(title: "Pho", 
                   cuisine: "Vietnamese", 
                   timeToMake: 45,
                   ingredients: ["Beef broth", "Rice noodles", "Star anise", "Cloves", "Cinnamon stick", "Ginger", "Garlic", "Onion", "Fish sauce", "Hoisin sauce", "Sugar", "Salt", "Pepper", "Cilantro", "Bean sprouts", "Lime wedges"],
                   instructions: ["Prepare the broth:",
                                  "a. In a large pot, combine beef broth, star anise, cloves, cinnamon stick, ginger, garlic, and onion.",
                                  "b. Add fish sauce, hoisin sauce, sugar, salt, and pepper to the pot.",
                                  "c. Bring the mixture to a boil, then reduce the heat to simmer. Let it simmer for 1-2 hours to develop flavors.",
                                  "Prepare the toppings:",
                                  "a. Prepare bean sprouts, cilantro, and lime wedges for serving.",
                                  "Cook the rice noodles according to package instructions.",
                                  "Strain the broth to remove solids and keep it hot.",
                                  "Assemble the Pho bowls:",
                                  "a. Place a portion of cooked rice noodles in each serving bowl.",
                                  "b. Pour the hot broth over the noodles, covering them well.",
                                  "c. Add desired toppings such as bean sprouts, cilantro, and lime wedges.",
                                  "Serve hot and enjoy your Pho!"],
                   imageName: "pho"),
        Favourites(title: "Tacos al Pastor", 
                   cuisine: "Mexican", 
                   timeToMake: 40,
                   ingredients: ["Pork shoulder", "Pineapple", "Adobo seasoning", "Orange juice", "White vinegar", "Annatto seeds", "Cilantro", "Onions", "Corn tortillas"],
                   instructions: ["Marinate the pork:",
                                  "a. In a blender, combine the adobo seasoning, orange juice, white vinegar, and annatto seeds.",
                                  "b. Blend until you have a smooth marinade.",
                                  "c. Place the pork shoulder in a large bowl and pour the marinade over it.",
                                  "d. Massage the marinade into the pork, ensuring it's well coated.",
                                  "e. Cover the bowl and refrigerate for at least 2 hours, or overnight for best results.",
                                  "Prepare the toppings:",
                                  "a. Dice the pineapple, chop the cilantro, and finely slice the onions.",
                                  "b. Set aside for assembling the tacos.",
                                  "Cook the marinated pork:",
                                  "a. Preheat a grill or grill pan over medium-high heat.",
                                  "b. Thread the marinated pork onto skewers or place directly on the grill.",
                                  "c. Cook for 15-20 minutes, turning occasionally, until the pork is cooked through and has a nice char.",
                                  "d. Remove the pork from the grill and let it rest for a few minutes.",
                                  "Assemble the tacos:",
                                  "a. Warm the corn tortillas on the grill or in a pan.",
                                  "b. Remove the pork from the skewers and place it on the tortillas.",
                                  "c. Top with diced pineapple, chopped cilantro, and sliced onions.",
                                  "Serve the Tacos al Pastor warm and enjoy!"],
                   imageName: "tacos-al-pastor"),
        Favourites(title: "Guacamole", 
                   cuisine: "Mexican", 
                   timeToMake: 15,
                   ingredients: ["Avocados", "Onions", "Lime juice", "Cilantro", "Salt", "Pepper"],
                   instructions: ["Peel and pit the avocados.",
                                  "In a medium bowl, mash the avocados with a fork or potato masher.",
                                  "Add the diced onions, lime juice, chopped cilantro, salt, and pepper to the mashed avocados.",
                                  "Stir all the ingredients together until well combined.",
                                  "Taste the guacamole and adjust the seasoning if needed.",
                                  "If you prefer a smoother consistency, you can use a blender or food processor to achieve the desired texture.",
                                  "Transfer the guacamole to a serving bowl.",
                                  "Cover the guacamole with plastic wrap, ensuring it directly touches the surface to prevent browning.",
                                  "Refrigerate for at least 30 minutes before serving to allow the flavors to meld.",
                                  "Serve the guacamole with tortilla chips or as a topping for tacos, nachos, or your favorite dishes."],
                   imageName: "guacamole"),
        Favourites(title: "Hummus", 
                   cuisine: "Middle Eastern", 
                   timeToMake: 20,
                   ingredients: ["Canned chickpeas", "Tahini", "Garlic", "Lemon juice", "Olive oil", "Salt", "Cumin"],
                   instructions: ["In a food processor, combine the following:",
                                  "a. Canned chickpeas",
                                  "b. Tahini",
                                  "c. Garlic",
                                  "d. Lemon juice",
                                  "e. Olive oil",
                                  "f. Salt",
                                  "g. Cumin",
                                  "Blend the ingredients until smooth and creamy.",
                                  "If the hummus is too thick, you can add a bit of water or more olive oil to achieve the desired consistency.",
                                  "Taste the hummus and adjust the seasonings as needed.",
                                  "Transfer the hummus to a serving bowl.",
                                  "Drizzle with a bit of olive oil and sprinkle with a pinch of cumin for garnish.",
                                  "Serve the hummus with pita bread, vegetables, or your favorite dipping choice."],
                   imageName: "hummus"),
    ]
}
